### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by hamidyaseen** [nigrosimone/ng-let#1]
Why not remove bootstrap and popperjs from dependencies

**Comment by nigrosimone** [comment]
Isn't into dependencies https://github.com/nigrosimone/ng-let/blob/main/projects/ng-let/package.json

```
"peerDependencies": {
  "@angular/common": "^10.0.6",
  "@angular/core": "^10.0.6"
},
"dependencies": {
  "tslib": "^2.0.0"
}
```
