### ISSUE TITLE
Incorrect type inference

### ISSUE THREAD

**Issue by aaditmshah** [nigrosimone/ng-let#3]
Consider the following Angular template.

```html
<div *ngLet="flag$ | async; let flag">
```

Here, `flag$` is an `Observable<boolean>`. Hence, I would expect `flag` to be `boolean | null`. It is nullable since the `async` pipe can return `null` when it doesn't have any values to return.

However, in VS Code when I hover over the `flag` variable then the type checker shows that it inferred the type as `true`, i.e. the only truthy value out of `true`, `false`, and `null`. This is incorrect. I can see from experimentation that falsy values are bound too.

**Comment by nigrosimone** [comment]
Thanks! I've fixed in version 15.0.2 https://www.npmjs.com/package/ng-let
