### ISSUE TITLE
Standalone Directive

### ISSUE THREAD

**Issue by KerickHowlett** [nigrosimone/ng-let#4]
Is there a way to have the `ngLet` directive work with standalone components?

**Comment by KerickHowlett** [comment]
Wait. Never mind. 😅

**Comment by JordanW9232** [comment]
> Wait. Never mind. 😅

I came here wondering the same thing, and am still not seeing that this is possible. Am I missing something?

**Edit:**

I know it works when importing `NgLetModule` in the standalone imports, but I was looking to just have `NgLetDirective` in my imports

**Comment by nigrosimone** [comment]
Import `NgLetModule` into standalone imports and it works. 

> I was looking to just have NgLetDirective in my imports

The `NgLetModule` only exports the `NgLetDirective`
```ts
import { NgModule } from '@angular/core';
import { NgLetDirective } from './ng-let.directive';

@NgModule({
  declarations: [NgLetDirective],
  exports: [NgLetDirective]
})
export class NgLetModule { }
```

`NgLet` it's just 1,67 KB (1.715 byte) and gzip 709 byte!

**Comment by nigrosimone** [comment]
From 18.0.3, is also standalone:

```ts
import { Component } from '@angular/core';
import { NgLetDirective } from 'ng-let';

@Component({
  selector: 'app-root',
  template: `
  <ng-container *ngLet="(num1 + num2) as total"> <!-- single computation -->
    <div>
      1: {{ total }} <!-- 3 -->
    </div>
    <div>
      2: {{ total }} <!-- 3 -->
    </div>
  </ng-container> 
  `,
  imports: [NgLetDirective]
})
export class AppComponent {
  num1: number = 1;
  num2: number = 2;
}
```
