### ISSUE TITLE
Typings lead to errors

### ISSUE THREAD

**Issue by nikita-fuchs** [nigrosimone/ng-let#5]
Hey, I came across your awesome package over a reply you posted on stackoverflow. I'm on typescript 4.8.4 and angular 15.2 . After installing and importing the module into my standalone component, I get the following error:

```
node_modules/ng-let/lib/ng-let.directive.d.ts:63:83 - error TS2344: Type '{ ngLet: { alias: "ngLet"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"ngLet"' is incompatible with index signature.
    Type '{ alias: "ngLet"; required: false; }' is not assignable to type 'string'.

63     static ɵdir: i0.ɵɵDirectiveDeclaration<NgLetDirective<any>, "[ngLet]", never, { "ngLet": { "alias": "ngLet"; "required": false; }; }, {}, never, never, false, never>;

```

However, if I just go into the package and disable typechecking here: `node_modules/ng-let/lib/ng-let.directive.d.ts`

```
//@ts-ignore
    static ɵdir: i0.ɵɵDirectiveDeclaration<NgLetDirective<any>, "[ngLet]", never, { "ngLet": { "alias": "ngLet"; "required": false; }; }, {}, never, never, false, never>;
```

it works perfectly fine. I'm using *ngLet on a div, which seems to work in the stackblitz example, too.

Maybe there is a simple fix? I'm not a big typescript ninja :)

**Comment by nigrosimone** [comment]
Hi, If you are on Angular 15 you need to install NgLet 15

```
npm i ng-let@15.0.2
```

**Comment by nikita-fuchs** [comment]
That worked, thanks ! 

Seriously, this is the most helpful package extending angular's core functionalities I've seen in all the years. Allows me to reduce boilerplate code on various places by 50%. Thank you so much for it.

**Comment by nigrosimone** [comment]
thanks! I have published some other Angular libraries, take a look:

 - [NgSimpleState: Simple state management in Angular with only Services and RxJS](https://www.npmjs.com/package/ng-simple-state)
 - [NgHttpCaching: Cache for HTTP requests in Angular application](https://www.npmjs.com/package/ng-http-caching)
 - [NgGenericPipe: Generic pipe for Angular application for use a component method into component template.](https://www.npmjs.com/package/ng-generic-pipe)
 - [NgForTrackByProperty: Angular global trackBy property directive with strict type checking](https://www.npmjs.com/package/ng-for-track-by-property)
